author:
  email:       contact@clermontech.fr
  url:         http://clermontech.org/

  gh:
    user:      clermontech
    repo:      clermontech.github.com

  twitter:     clermontech

  disqus:
    shortname: clermontech

permalink:     none
