permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/ ]

flickr_id: 96523012@N07

base_url: http://clermontech.org

rss:
    title: "Clermont'ech"
    author: "Clermont'ech"
    email: "hello@clermontech.org"

#announcement:
#    href:
#    message:
